import { StyleSheet } from 'react-native';

/** Shared layout for create-box / join-box onboarding cards. */
export const phoneCardFlowStyles = StyleSheet.create({
  gradient: { flex: 1 },
  page: {
    flex: 1,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  phoneCard: {
    width: '96%',
    height: '70%',
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.95)',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 14 },
    shadowRadius: 20,
    elevation: 8,
  },
  header: {
    minHeight: 98,
    backgroundColor: '#F2C572',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerStacked: {
    minHeight: 160,
    backgroundColor: '#F2C572',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  backPill: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  backPillAbsolute: {
    position: 'absolute',
    left: 16,
    top: 16,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '800',
    color: '#FEFDF9',
  },
  headerTitleCentered: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '800',
    color: '#FEFDF9',
    textAlign: 'center',
  },
  headerSub: {
    marginTop: 4,
    fontSize: 14,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '500',
  },
  headerSubCentered: {
    marginTop: 6,
    fontSize: 15,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '500',
    textAlign: 'center',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 20,
    gap: 10,
  },
  contentFlex: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 12,
  },
  sectionHint: {
    marginTop: 4,
    fontSize: 12,
    color: '#9A8F86',
    fontWeight: '600',
  },
  textInput: {
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: '#EFE3D3',
    paddingHorizontal: 14,
    color: '#2E2A26',
    fontSize: 16,
    fontWeight: '600',
  },
  footerWrap: {
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  footerButton: {
    height: 51,
    borderRadius: 16,
    backgroundColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 8,
    elevation: 3,
  },
  footerButtonActive: {
    backgroundColor: '#2F80ED',
  },
  footerButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  checkCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
});
